### ISSUE TITLE
Equip sound is played everytime the player travels through dimensions

### ISSUE THREAD

**Issue by Insane96** [InsomniaKitten/ArmorSoundTweak#1]
If it has armor on.
The sound is played _x_ times, for _x_ armor pieces the player has equipped.

This might be related to the fact that internally the game spawns the player in the dimensions with nothing, and as soon as he loads the armor is equipped so the sound is played

**Comment by ChloeDawn** [comment]
Which Minecraft + Forge versions does this happen on?

**Comment by Insane96** [comment]
1.11 Armor Sound Tweaks 2.0.1 iirc

**Comment by ChloeDawn** [comment]
Fixed in https://github.com/InsomniaKitten/ArmorSoundTweak/commit/532af9c3069a4e2cd19fc4bf5afe64f100ee9cb1
