### ISSUE TITLE
[1.16.5-Forge-Suggestion] Mark mod as client side only, makes server "fml server incompatible" in server list.

### ISSUE THREAD

**Issue by Gbergz** [InsomniaKitten/ArmorSoundTweak#3]
Title ^

**Versions**
- ArmorSoundTweak: [3.0.0](https://www.curseforge.com/minecraft/mc-mods/armor-sound-tweak/files/3153642)
- Forge: 36.1.62
- Additional mod(s) No mods.

**Describe the bug**
If mod is missing on server it makes the server ping "Incompatible FML Modded Server".

**To Reproduce**
1. Install mod on client.
2. Don't install on server. (**Because it crashes.**)
3. Add server to multiplayer list.
4. Ping it.
5. "Incompatible FML Modded Server".
![image](https://user-images.githubusercontent.com/26634554/119142325-a8f46c80-ba46-11eb-947f-4f96413ce50c.png)

**Expected behavior**
That the modlist is compatible. showing a green checkmark like below:
![image](https://user-images.githubusercontent.com/26634554/119153248-5ec4b880-ba51-11eb-9e2d-7918e8d27fda.png)

**Additional context**
If possible, mark mod as client only.

**Comment by ChloeDawn** [comment]
I fixed this in-dev a while back but then forgot to make a release, my apologies! I'll have an update out later today!

**Comment by ChloeDawn** [comment]
Fixed in https://github.com/ChloeDawn/ArmorSoundTweak/releases/tag/3.1.0-forge https://www.curseforge.com/minecraft/mc-mods/armor-sound-tweak/files/3396535

Apologies for the delay in getting this hotfix released!
